### PR TITLE
Adding an option to use FOXSI PSF that includes wing data

### PR DESCRIPTION
**Pull request by aringlis**
Amendments to the FOXSI PSF. I tested it locally but someone else should try it out.
- Adding a option in foxsi_get_psf_map to return a PSF that includes wing data.
- Call using the keyword 'include_wings'
- Currently For on-axis PSF only

### CODE REVIEW

**Comment by LinErinG** [comment]
@aringlis I noticed you changed the title from WIP to non-WIP.  Does that mean it's ready for us to test and merge or are you still editing it?

**Comment by aringlis** [comment]
@LinErinG yes, it's ready to test.

**Comment by LinErinG** [comment]
@aringlis I tried the code and it ran with no errors, but the resulting PSF looks asymmetric to me.  (See screenshot.)  Is this intentional?

psf_w_wo_wings

The code I used was:

psf0 = foxsi_get_psf_map(inc=0)
psf1 = foxsi_get_psf_map
!p.multi=[0,2,1]
plot_map, psf0, /log, dmin=min(psf1.data), dmax=max(psf1.data), title='FOXSI PSF w/o wings'
plot_map, psf1, /log, dmin=min(psf1.data), dmax=max(psf1.data), title='FOXSI PSF with wings'
!p.multi=0

A small request (assuming it's easy): Since the default is to include the wings, it would be nice if the keyword were "no_wings" or something equivalent instead of "include_wings."  This is only requested to make it more intuitive for the user.  /no_wings is more intuitive than include_wings=0, and the converse case (/include_wings) is never needed.  If this requires detailed reformulating of your logical expressions then I'd say don't worry about it.

**Comment by aringlis** [comment]
@LinErinG - thanks for testing the code. I wouldn't say 'intentional', but the new PSF is asymmetric in the sense that the best fit to the on-axis data is slightly elliptical. This was probably true for the old PSF too - it looks like it was forced to be radially symmetric in the code. I can make the same correction for this PSF.

I'll change the keyword logic as well.

**Comment by ehsteve** [comment]
@aringlis did you fix the PSF asymmetry?

**Comment by aringlis** [comment]
@ehsteve @LinErinG - asymmetry fixed now.

**Comment by LinErinG** [comment]
This looks good to me.  The PSF now looks symmetric, and a cut across it shows a small increase in flux far from the center.  I'll merge this later today if there are no other comments.

psf-test

psf-test2

**Pull request merged**
