### PR TITLE
Updating FOXSI effective area response

### PR DESCRIPTION
**Pull request by aringlis**
Updating the FOXSI response function - configuration is 14m, 2 modules, 20 shells. Addresses #38 

@ehsteve @LinErinG  - is effective_area_per_shell.csv still used in the code? shell_parameters.csv also exists and seems to be called by the solitary function foxsi_get_optics_properties.pro. I will update this with the new shell parameters, but do we want to retain this?

This addresses issue number #43.

### CODE REVIEW

**Comment by ehsteve** [comment]
@aringlis ignore the shell_parameters.csv file for now. The purpose of that was to allow people to play with the different shells but we don't need to do that right now.

**Comment by ehsteve** [comment]
I would also remove any mention of different configurations as we only have one. No need to needlessly confuse people.

**Comment by aringlis** [comment]
@ehsteve ok will do - I had only kept the configuration parameter for backwards compatibility.

**Comment by LinErinG** [comment]
Test-ran this and everything looked fine, so I'll merge it.

**Pull request merged**
