### PR TITLE
Doubling rate limits and several small improvements

### PR DESCRIPTION
**Pull request by LinErinG**
There's a lot here, but each change is small.  The rundown, in approx order of importance:

-- Doubled the rate limits (per-detector and per-threshold) since we have two detectors, not one.

-- Added more information printed to screen at the end of foxsi_get_output_image_cube, including rate info and the attenuator info, whether _or not_ rate limits are exceeded.

-- Added pass-through of keyword "SHUTTER_THICKNESS_MM" to foxsi_get_output_image_cube so that the shutter thickness can be controlled manually.

-- Adjusted parameters again for the default source map, so the default source will trigger a warning with no attenuator, but will not if an attenuator is inserted.  (Adjustment was necessary since I changed the rate limits.)

-- Removed some unhelpful warnings, like when we renormalize an image cube after binning it to conserve flux.  (This doesn't need to be warned about.)

### CODE REVIEW

**Comment by ayshih** [comment]
I don't think we need to raise a fuss about a messy commit history on this particular repo, but in principle you "should" do a rebase or use cherry-pick so that you only ask to merge the relevant commits.

**Comment by LinErinG** [comment]
@ayshih I don't think we realistically want to wait for me to learn to do that, but that's noted for future projects.

**Comment by ayshih** [comment]
While you're at it, can you also tweak the rate-warning text so that it doesn't assume that an attenuator wasn't used?  I especially find it annoying that it suggests `SHUTTER_STATE = 1` even if I'm already using state 2.

**Comment by LinErinG** [comment]
@ayshih Ok, done.  Now the rate warnings don't give the extra info about how to use the shutter if the shutter was already used.

**Comment by ayshih** [comment]
:+1:, but created a clean version of the PR (see #54) so there aren't the spurious deconvolution commits, and closing this PR.

**Pull request closed without merging**
